[project]
name = "insurance-claim-assistant"
version = "0.1.0"
# description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.1.0",
    "flask_cors",
    "requests",
    "numpy",
    "openai",
    "python-dotenv",
]
